# First Finger (Index finger)
sh_rh_ffj0_effort_controller:
  type: sr_mechanism_controllers/SrhEffortJointController
  joint: rh_FFJ0
  max_force: 10
  friction_deadband: 0
sh_rh_ffj3_effort_controller:
  type: sr_mechanism_controllers/SrhEffortJointController
  joint: rh_FFJ3
  max_force: 10
  friction_deadband: 0
sh_rh_ffj4_effort_controller:
  type: sr_mechanism_controllers/SrhEffortJointController
  joint: rh_FFJ4
  max_force: 10
  friction_deadband: 0


# Middle Finger
sh_rh_mfj0_effort_controller:
  type: sr_mechanism_controllers/SrhEffortJointController
  joint: rh_MFJ0
  max_force: 10
  friction_deadband: 0
sh_rh_mfj3_effort_controller:
  type: sr_mechanism_controllers/SrhEffortJointController
  joint: rh_MFJ3
  max_force: 10
  friction_deadband: 0
sh_rh_mfj4_effort_controller:
  type: sr_mechanism_controllers/SrhEffortJointController
  joint: rh_MFJ4
  max_force: 10
  friction_deadband: 0


# Ring Finger
sh_rh_rfj0_effort_controller:
  type: sr_mechanism_controllers/SrhEffortJointController
  joint: rh_RFJ0
  max_force: 10
  friction_deadband: 0
sh_rh_rfj3_effort_controller:
  type: sr_mechanism_controllers/SrhEffortJointController
  joint: rh_RFJ3
  max_force: 10
  friction_deadband: 0
sh_rh_rfj4_effort_controller:
  type: sr_mechanism_controllers/SrhEffortJointController
  joint: rh_RFJ4
  max_force: 10
  friction_deadband: 0


# Little Finger
sh_rh_lfj0_effort_controller:
  type: sr_mechanism_controllers/SrhEffortJointController
  joint: rh_LFJ0
  max_force: 10
  friction_deadband: 0
sh_rh_lfj3_effort_controller:
  type: sr_mechanism_controllers/SrhEffortJointController
  joint: rh_LFJ3
  max_force: 10
  friction_deadband: 0
sh_rh_lfj4_effort_controller:
  type: sr_mechanism_controllers/SrhEffortJointController
  joint: rh_LFJ4
  max_force: 10
  friction_deadband: 0
sh_rh_lfj5_effort_controller:
  type: sr_mechanism_controllers/SrhEffortJointController
  joint: rh_LFJ5
  max_force: 10
  friction_deadband: 0


# Thumb
sh_rh_thj1_effort_controller:
  type: sr_mechanism_controllers/SrhEffortJointController
  joint: rh_THJ1
  max_force: 10
  friction_deadband: 0
sh_rh_thj2_effort_controller:
  type: sr_mechanism_controllers/SrhEffortJointController
  joint: rh_THJ2
  max_force: 10
  friction_deadband: 0
sh_rh_thj3_effort_controller:
  type: sr_mechanism_controllers/SrhEffortJointController
  joint: rh_THJ3
  max_force: 10
  friction_deadband: 0
sh_rh_thj4_effort_controller:
  type: sr_mechanism_controllers/SrhEffortJointController
  joint: rh_THJ4
  max_force: 10
  friction_deadband: 0
sh_rh_thj5_effort_controller:
  type: sr_mechanism_controllers/SrhEffortJointController
  joint: rh_THJ5
  max_force: 10
  friction_deadband: 0


# Wrist
sh_rh_wrj1_effort_controller:
  type: sr_mechanism_controllers/SrhEffortJointController
  joint: rh_WRJ1
  max_force: 10
  friction_deadband: 0
sh_rh_wrj2_effort_controller:
  type: sr_mechanism_controllers/SrhEffortJointController
  joint: rh_WRJ2
  max_force: 10
  friction_deadband: 0


