<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:macro name="dark_grey" >
    <material name="dark_grey">
      <color rgba="0.21961 0.21961 0.21961 1.0" />
    </material>
  </xacro:macro>
  <xacro:macro name="light_grey" >
    <material name="light_grey">
      <color rgba="0.90000 0.90000 0.90000 1.0" />
    </material>
  </xacro:macro>
  <xacro:if value="${mounting_plate}">
    <xacro:property name="mounting_plate_offset" value="0.006" />
  </xacro:if>
  <xacro:unless value="${mounting_plate}">
    <xacro:property name="mounting_plate_offset" value="0.0" />
  </xacro:unless>
  <xacro:macro name="forearm" params="hand_type:=^ hand_version:=^ prefix:=^ mounting_plate:=^">
    <link name="${prefix}forearm">
      <inertial>
        <origin xyz="0 0 0.09" rpy="0 0 0" />
        <mass value="3.0" />
        <inertia ixx="0.0138" ixy="0.0" ixz="0.0" iyy="0.0138" iyz="0.0" izz="0.00744" />
      </inertial>
      <visual>
        <origin xyz="0 0 ${mounting_plate_offset}" rpy="0 0 0" />
        <geometry name="${prefix}forearm_visual">
          <mesh filename="package://sr_description/meshes/components/forearm/forearm_${hand_version}.dae" scale="0.001 0.001 0.001" />
        </geometry>
        <xacro:light_grey/>
      </visual>
      <collision>
        <origin xyz="0 0 ${mounting_plate_offset}" rpy="0 0 0" />
        <geometry name="${prefix}forearm_collision">
          <mesh filename="package://sr_description/meshes/components/forearm/forearm_collision_${hand_version}.dae" scale="0.001 0.001 0.001" />
        </geometry>
      </collision>
      <!-- wrist mount -->
      <collision>
        <origin xyz="0 -0.01 ${0.181+mounting_plate_offset}" rpy="0 0.78 0" />
        <geometry>
          <box size="0.07 0.07 0.07" />
        </geometry>
      </collision>
      <!-- mounting plate in case the hand is attached to an arm -->
      <xacro:if value="${mounting_plate}">
        <visual>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry name="${prefix}mounting_plate">
            <mesh filename="package://sr_description/meshes/components/mounting_plate/mounting_plate_${hand_version}.dae" scale="0.001 0.001 0.001" />
          </geometry>
        </visual>
        <collision>
          <origin xyz="0 0 0.002" rpy="0 0 0" />
          <geometry>
            <cylinder radius="0.0675" length="0.008" />
          </geometry>
        </collision>
      </xacro:if>
      <!-- TODO: Make a decision on whether to add the connector or not -->
      <!--visual>
        <origin rpy="0 -1.57 -1.57" xyz="0.0 0.067 0.0045"/>
        <geometry name="${prefix}cable_extr_visualisation">
          <mesh filename="package://sr_description/meshes/components/cable_connector/cable_connector_base_${hand_version}.dae" scale="0.001 0.001 0.001" />
        </geometry>
      </visual-->
    </link>
    <gazebo reference="${prefix}forearm">
      <selfCollide>false</selfCollide>
    </gazebo>
  </xacro:macro>
</robot>
